export const ISLOADING = 'ISLOADING';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const TOTAL_STUDENTS = 'TOTAL_STUDENTS';


